### ISSUE TITLE
Deploy FetchVerticle as a worker

### ISSUE THREAD

**Issue by tsegismont** [Sammers21/rss-reader#11]
It makes use of blocking APIs

**Comment by Sammers21** [comment]
Where the verticle gets blocked? You mean when parsing XML?

**Comment by tsegismont** [comment]
I may have overlooked this. The verticle uses blocking APIs but the source is purely in memory, correct?

**Comment by Sammers21** [comment]
@tsegismont, yes, an XML got parsed after downloading it via HTTP. The operation will block thread only if it the XML is huge.

**Comment by tsegismont** [comment]
That's fine then. Ideally, we would stream the RSS content to disk then read back from the downloaded file to avoid memory consumption problems. But that's just a demo :stuck_out_tongue:
